Content
JuezUN/juezun.github.io pull request #5
Opened 2020-10-15 16:39 UTC by Heldeg

2020-10-15 16:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JuezUN/UNCode_page?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JuezUN/UNCode_page?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JuezUN/UNCode_page?pullRequest=5) it.</sub>

2020-10-19 22:19 UTC, crdgonzalezca requested changes
There are some suggested changes, but in general it looks good!
I also suggest changing how files are organized and the internal directories:

```
/UNCode_page
   /assets
        /css
        /js
        /img
        /resources
    /pages -> rather than /html.
    index.html
    ...
    ...
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +    <title>UnCode|Contribuidores</title>
```suggestion
    <title>UNCode | Contribuidores</title>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <img src="../img/LogoUN.png" class="img-circle" width="100" height="100">
In case the person has a photo on GitHub, we can set the GitHub image URL here of that user. Do this for all contributors.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniero de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Estudiante de Ingeniería de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
By now, we can remove this text. I think we are not going to set something here for all contributors.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                        <a href="https://github.com/0xDCA" class="mr-2 text-dark lead"><i
This button is too small I think. Fix for all.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniero de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Estudiante de Maestría en Ingeniería de Sistemas y Computación</h6>
```
I not quite sure, @ferestrepoca can confirm this.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
@ferestrepoca Can you confirm studies field of Giovanny?

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Estudiante de Ingeniería de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Profesor Titular, Departamento de Ingeniería  de Sistemas e Industrial - Universidad Nacional de Colombia, Bogotá</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Profesor Titular, Departamento de Ingeniería  de Sistemas e Industrial - Universidad Nacional de Colombia, Bogotá</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
Set your major: Estudiante de ...?

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Estudiante de Ingeniería de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Estudiante de Maestría en Ingeniería de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniera de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniero de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniero de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
```suggestion
                    <h6 class="card-subtitle mb-2 text-muted">Ingeniero de Sistemas y Computación</h6>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                                    class="icon ion-logo-github lead mr-3 align-middle"></i>Github</a></small>
```suggestion
                                    class="icon ion-logo-github lead mr-3 align-middle"></i>GitHub - Oganización</a></small>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                                        class="material-icons lead mr-3 align-middle text-light">mail_outline</i>uncode_fibog@unal.edu.co
```suggestion
                                        class="material-icons lead mr-3 align-middle text-light">mail_outline</i><a href="mailto:uncode_fibog@unal.edu.co">uncode_fibog@unal.edu.co</a>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                            <a href="contributors.html" class="text-light">Contribuidores</a>
Rather than putting the page here, set something like 'Subir', and the `href` set it to "#".

2020-10-19 22:19 UTC, crdgonzalezca commented on html/contributors.html
> +                <div class="col-lg-4 py-2">
Also set the UNCode logo as it is done in the header

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
This is a too old version of JQuery, update to the latest if possible. See https://code.jquery.com/

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +    <title>UnCode|Documentación</title>
```suggestion
    <title>UNCode | Documentación</title>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +<header>
Is it possible to move the header to a separate html script? you can try loading this separate file with JavaScript or JQuery. See https://stackoverflow.com/questions/8988855/include-another-html-file-in-a-html-file, this might help.

As the header is shared across all the pages, having a separate only one file with the header, help us to maintain the web page.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +                <a class="nav-link" href="https://github.com/JuezUN/INGInious/wiki">Wiki
```suggestion
                <a class="nav-link" href="https://github.com/JuezUN/INGInious/wiki">UNCode Wiki
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +                        <a class="nav-link">Documentación</a>
Every time a click is done in documentation, a pdf is downloaded, fix this.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +<footer>
As well as in the Header, try to put the footer in separate file.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/documentation.html
> +    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
JQuery is already imported at the of the file.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +    <title>UnCode|Publicaciones</title>
```suggestion
    <title>UNCode | Publicaciones</title>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                        <p class="">Este documento hace una introducción a UNCode, una plataforma para el
I think it is better to set the abstract, it does not matter whether it is in English. The abstract is more precise.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                            PROGRAMMING SKILLS</h2>
```suggestion
                        <h2 class="">UNCode: Interactive system for learning and automatic evaluation of computer programming skills</h2>
```
Check first with @ferestrepoca

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                            <a onclick="cite('uncode-cite-1-container',this.id)" id="uncode-cite-1" type="button"
Rather than copying the cite, display the cite below when a click is done on this. Like a panel that opens and closes. Other option is using a modal.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                                2018.</small></p>
```suggestion
                            <p class="font-italic box-line p-1" id="uncode-cite-1-cite"><small>F. Restrepo-Calle, J.J. Ramírez-Echeverry, F.A. Gonzalez. "UNCode: Interactive system for learning and automatic evaluation of computer programming skills.". In Proceedings of the 10th annual International Conference on Education and New Learning Technologies EDULEARN 2018. Palma de Mallorca, Spain, 2nd-4th July 2018, pp. 6888-6898. doi: 10.21125/edulearn.2018.1632.</small></p>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                        <div class="row px-4 collapse py-2" id="uncode-cite-1-container">
Also add other type of cite called BibTex, so there are two options to cite this publication. This is as follows:
```
    @InProceedings{Restrepo-Calle2018,
        author = {Restrepo-Calle, F. and Ram{\'{i}}rez-Echeverry, J.J. and Gonzalez, F.A.},
        title = {{UNCode: Interactive System for Learning and Automatic Evaluation of Computer Programming Skills}},
        series = {10th International Conference on Education and New Learning Technologies},
        booktitle = {EDULEARN18 Proceedings},
        isbn = {978-84-09-02709-5},
        issn = {2340-1117},
        doi = {10.21125/edulearn.2018.1632},
        url = {http://dx.doi.org/10.21125/edulearn.2018.1632},
        publisher = {IATED},
        location = {Palma, Spain},
        month = {2-4 July, 2018},
        year = {2018},
        pages = {6888-6898}
    }
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                                programming course supported by a software tool," in CAEE, 27(1), 80-89, 2019.</small>
```suggestion
                            <p class="font-italic box-line p-1" id="uncode-cite-2-cite"><small>Restrepo‐Calle, F, Ramírez Echeverry, JJ, González, FA. Continuous assessment in a computer programming course supported by a software tool. Comput Appl Eng Educ. 2019; 27: 80– 89. https://doi.org/10.1002/cae.22058</small>
```
@ferestrepoca is this change correct?

2020-10-19 22:19 UTC, crdgonzalezca commented on html/publications.html
> +                               title="Referencia copiada" aria-controls="#uncode-cite-2-container">Cómo Citar</a>
Same as before, toggle a window to show the citation rather than copy it.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +    <title>UnCode|Repositorios</title>
```suggestion
    <title>UNCode | Repositorios</title>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                                   aria-selected="false">INGInious container</a>
```suggestion
                                   aria-selected="false">INGInious containers</a>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                                   aria-selected="false">Online Python Tutor</a>
```suggestion
                                   aria-selected="false">Python Tutor</a>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                            </li>
Remove, as this repo was archived.

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                            </li>
This is not the anymore

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                            <a href="https://github.com/JuezUN/" class="btn btn-dark mr-2 mb-4">Ir a Github</a>
```suggestion
                            <a href="https://github.com/JuezUN/" class="btn btn-dark mr-2 mb-4">Ir a GitHub</a>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on html/repositories.html
> +                            <p>Es el juez encargado de evaluar automáticamente el código escrito por los
Update every repository description with the description in the repos' README as this is more accurate now.

2020-10-19 22:19 UTC, crdgonzalezca commented on index.html
> +                            Jupyter. </p></div>
```suggestion
                        <h2>Múltiples formas de trabajar</h2>
                        <p>Con UNCode puedes trabajar con múltiples lenguajes de programación para solucionar
                            tus ejercicios de programación, entre estos están Python, C, C++ y Java. Así como también puedes desarrollar tus tareas con lenguajes descriptivos de hardware como VHDL y
                            Verilog. Además, se aceptan Jupyter Notebooks para evaluar tus tareas. </p></div>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on index.html
> +                    de aprendizaje en lugar de concursos de programación competitiva.</p>
```suggestion
                <p>UNCode posee un sistema de calificación automática de tareas de programación basado en <a
                        href="https://inginious.org/">INGInious</a>. Esto se hace de manera flexible,
                    segura, escalable y configurable para tus objetivos. Adicionalmente, feedback automático e imediato es entregado a los estudiantes. </p>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on index.html
> +                    pruebas de entrada y salida personalizables, y plantillas de código para tareas de programación.
```suggestion
                    para hacer recomendaciones de buenas prácticas, visualizador de código en ejecución en Python tutor (link to python tutor), entorno de
                    pruebas de entrada y salida personalizables, plantillas de código para tareas de programación, entre otras.
```

2020-10-19 22:19 UTC, crdgonzalezca commented on index.html
> +                    forma de grafo, las cuales apoyan la labor de docencia.</p>
```suggestion
                <p>UNCode cuenta con un asistente para la creación fácil y automática de tareas, banco de problemas de programación, un modulo de
                    evaluación manual, generador de reportes anti plagio, visualizador de espacio de soluciones en
                    forma de grafo (las cuales apoyan la labor de docencia), entre otras.</p>
```

2020-10-19 22:19 UTC, crdgonzalezca commented on js/documentation.js
> +    let id = $(this).find('a').attr('id');
```suggestion
    const id = $(this).find('a').attr('id');
```

2020-10-19 22:19 UTC, crdgonzalezca commented on js/documentation.js
> +    let id = $(this).find('a').attr('id');
Make sure to use const whenever the instance assignation does not change, this helps to other programmers to understand faster the code.

2020-10-19 22:19 UTC, crdgonzalezca commented on js/documentation.js
> +        let IDs = []
```suggestion
        let IDs = [];
```

2020-10-19 22:19 UTC, crdgonzalezca commented on js/documentation.js
> +        let IDs = []
Set semicolons to all the lines. I know it is not necessary in JS but it is a good practice and helps code review.

2020-10-19 22:19 UTC, crdgonzalezca commented on js/publications.js
> +    console.log(id_ref);
Remove console.log.

2020-10-19 22:19 UTC, crdgonzalezca commented on js/publications.js
> +    let aux = document.createElement("input");
```suggestion
    const aux = document.createElement("input");
```

2020-10-19 22:19 UTC, crdgonzalezca commented on js/publications.js
> +    console.log(id);
Remove log

2020-10-27 22:07 UTC, ferestrepoca requested changes
@Heldeg please complete the request changes.

2020-10-27 22:07 UTC, ferestrepoca commented on html/publications.html
> +                            de aprendizaje mediante la aplicación de encuestas.</p>
Please use the paper abstract.

2020-10-27 22:07 UTC, ferestrepoca commented on html/publications.html
> +                                programming course supported by a software tool," in CAEE, 27(1), 80-89, 2019.</small>
Yes, it is correct.

2020-10-27 22:07 UTC, ferestrepoca commented on html/publications.html
> +                                report," in GJEE, 22(3), In press, 2020.</small></p>
Update this reference.

2020-10-27 22:07 UTC, ferestrepoca commented on html/contributors.html
> +                    <h5 class="card-title">andrescorso</h5>
Andrés Corso

2020-10-27 22:07 UTC, ferestrepoca commented on html/contributors.html
> +                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
Yes, he is.

2020-10-27 22:07 UTC, ferestrepoca commented on html/contributors.html
> +                        <a href="https://github.com/ferestrepoca" class="mr-2 text-dark lead"><i
Update link to: https://dis.unal.edu.co/~ferestrepoca/

2020-10-27 22:07 UTC, ferestrepoca commented on html/contributors.html
> +                        <a href="https://github.com/fagonzalezo" class="mr-2 text-dark lead"><i
Update link to: https://dis.unal.edu.co/~fgonza/

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                            Jupyter. </p></div>
```suggestion
                        <h2>Múltiples entornos de evaluación</h2>
                        <p>Con UNCode puedes trabajar con múltiples lenguajes de programación 
                            como Python, Java, C y C++. También, utiliza lenguajes de descripción de hardware como VHDL y
                            Verilog. Además, puedes desarrollar e interactúar con actividades propuestas en notebooks de
                            Jupyter. </p></div>
```

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                    de aprendizaje en lugar de concursos de programación competitiva.</p>
```suggestion
                    de aprendizaje en lugar de competiciones de programación.</p>
```

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                    semántica, mantenimiento de código y realización de pruebas. Para esto cuenta con un "<a
```suggestion
                <p>UNCode apoya el proceso de aprendizaje de los estudiantes mediante la evaluación automática con retroalimentación inmediata. La realimentación es sumativa y formativa. La parte sumativa se le informa a los estudiantes por medio de una calificación numérica. La realimentación formativa abarca varios aspectos de la programación, donde destaca la sintaxis, semántica, mantenimiento de código y realización de pruebas personalizadas. Para esto cuenta con un "<a
```

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                    forma de grafo, las cuales apoyan la labor de docencia.</p>
```suggestion
                <p>UNCode cuenta con un asistente de calificación, banco de problemas de programación, un módulo de
                    evaluación manual, generador de reportes anti plagio, los cuales apoyan la labor docente.</p>
```

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                <p>UNCode cuenta con un modulo generador de reportes estadísticos interactivos para estudiantes y
```suggestion
                <p>UNCode cuenta con un módulo generador de reportes estadísticos interactivos para estudiantes y
```

2020-10-27 22:07 UTC, ferestrepoca commented on index.html
> +                                <p>UNCode está bajo el licenciamiento GNU AGPL v3 </p>
Put a link to the license

2020-11-06 05:09 UTC, crdgonzalezca approved these changes

2020-11-06 05:10 UTC, merged